services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db_doms
      MYSQL_PASSWORD: password
      MYSQL_USER: do_user
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: php:8.2-apache
    build: ./Dockerfile

    volumes:
      - "./app/public:/var/www/html"
    ports:
        - "80:80"
        - "443:443"
    networks:
      - lamp-docker

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker

networks:
    lamp-docker:
     driver: bridge
